### ISSUE TITLE
Meta-. in cider does not work with symbols having quotes (') in them.

### ISSUE THREAD

**Issue by firesofmay** [gfredericks/test.chuck#13]
While I was writing tests for com.gfredericks.test.chuck.generators-test ns, I notice that com.gfredericks.test.chuck.generators has been aliased as gen'

And when I try to jump into the definition of say gen'/for it fails, since cider thinks ' as an actual quote and does not understand it thus resulting in symbol not found.

It would be nice if such names in the project were renamed. 
Like gen' could be cgen (from chuck-gen).

Here's from cider docs what "M-." is:
Jump to the definition of a symbol. If invoked with a prefix argument, or no symbol is found at point, prompt for a symbol.

If this sounds okay to you, i'll be happy to add a patch for it as well.
Thanks.

**Comment by gfredericks** [comment]
I can sympathize with this because I've had similar issues, but this would technically be a cider problem (or whatever underlying thing is interpreting the clojure syntax). For some reason I have a soft spot in my heart for `foo'`-style names.

Clojure itself has a few, e.g. `*'`, `+'`, etc.

I'll ponder this for a bit but my inclination is to keep it as is.

**Comment by noisesmith** [comment]
I think `(modify-syntax-entry ?\' "'_" (syntax-table))` here https://github.com/clojure-emacs/clojure-mode/blob/master/clojure-mode.el#L168 might do the trick?

**Comment by gfredericks** [comment]
closing this since the fix to clojure-mode is allegedly pretty easy
