### ISSUE TITLE
Could not locate com/gfredericks/test/chuck/generators__init.class or com/gfredericks/test/chuck/generators.clj on classpath

### ISSUE THREAD

**Issue by tzach** [gfredericks/test.chuck#38]
Hi
I'm trying to use chuck generators:

lein project:
```
 [com.gfredericks/test.chuck "0.2.1"]
```

source:
```
  (:require [clojure.test.check :as tc]
            [clojure.test.check.generators :as gen]
            [clojure.test.check.properties :as prop]
            [com.gfredericks.test.chuck :as chuck]
            [com.gfredericks.test.chuck.generators :as cgen]
            )
```

evaluate:
```
FileNotFoundException Could not locate com/gfredericks/test/chuck/generators__init.class or com/gfredericks/test/chuck/generators.clj on classpath:   clojure.lang.RT.load (RT.java:443)
```

This work fine: ```[com.gfredericks.test.chuck :as chuck]```
Look like the generators are missing from the jar or something

**Comment by nberger** [comment]
Are you using clojure `1.7.0`? Since version `0.2.0` test.chuck dropped support for clojure `1.6.0`

From the error message I can see that clojure is not looking for `com/gfredericks/test/chuck/generators.cljc` which is where the generators namespace is defined. Support for `cljc` files was introduced in clojure "1.7.0", so it's usual to see this kind of error message when using an older clojure version.

**Comment by tzach** [comment]
> Are you using clojure 1.7.0? Since version 0.2.0 test.chuck dropped support for clojure 1.6.0

Yes I was using 1.6.0 :open_mouth:
Updating to 1.7.0 made all my problems goes ways.

Thanks!

**Comment by nberger** [comment]
Cool, no problem!
